Repository home-assistant/developers.home-assistant, pull requests merged in 2018-10, with the labels that each got.

#97 Add pressure sensor device class
  docs/entity_sensor.md
Labels: cla-signed

#99 Fixed IoT class link to blog
  docs/documentation_create_page.md
Labels: cla-signed

#98 Add virtual environment info to testing (tox) doc
  docs/development_testing.md
Labels: cla-signed, hacktoberfest

#102 Add internal to IQS
  docs/integration_quality_scale_index.md
Labels: cla-signed

#105 Update list/map (fixes #104)
  docs/documentation_create_page.md
  docs/documentation_standards.md
Labels: cla-signed

#103 Instruct OSX developers to install autoconf
  docs/development_environment.md
Labels: cla-signed

#101 Add missing header for generating keys
  docs/hassio_debugging.md
Labels: cla-signed

#100 Fix the links, typos and spelling
  docs/documentation_create_page.md
Labels: cla-signed

#109 Add missing options
  docs/documentation_create_page.md
  docs/documentation_standards.md
Labels: cla-signed

#108 Config folder location clarification
  docs/development_environment.md
Labels: cla-signed

#110 Fix linkable_title artifact
  docs/documentation_standards.md
Labels: cla-signed, hacktoberfest

#111 Spelling, wording
  docs/documentation_index.md
Labels: cla-signed, hacktoberfest

#112 Mention Netlify preview, move sentences
  docs/documentation_index.md
Labels: cla-signed, hacktoberfest

#114 Update instructions for Windows
  docs/development_environment.md
Labels: cla-signed

#116 Update documentation_index.md
  docs/documentation_index.md
Labels: cla-signed

#120 Updated readme
  README.md
Labels: cla-signed, hacktoberfest

#122 Simplify locating how to add dependencies to test environment
  docs/development_testing.md
Labels: cla-signed

#121 Remove gitignore-example and PR note
  .gitignore-example-from-docusaurus
  docs/development_submitting.md
Labels: cla-signed, hacktoberfest

#113 Added water heater doc.
  docs/entity_water_heater.md
  website/i18n/en.json
  website/sidebars.json
Labels: cla-signed

#124 Grammar fix
  docs/frontend_architecture.md
Labels: hacktoberfest

#126 Update documentation_index.md
  docs/documentation_index.md
Labels: cla-signed

#125 Type boolean requires documentation default.
  docs/documentation_create_page.md
Labels: cla-signed

#118 Add permissions
  docs/auth_index.md
  docs/auth_permissions.md
  website/i18n/en.json
  website/sidebars.json
  website/static/img/en/auth/architecture.png
Labels: cla-signed

#129 Prepend rake with bundle exec
  docs/documentation_index.md
Labels: cla-signed

#130 Made the minimum Python version explicit
  docs/development_index.md
Labels: cla-signed

#131 Use tox-venv to allow tests to run on OSX
  docs/development_testing.md
Labels: cla-signed

#132 Add docs for signed path
  docs/auth_api.md
Labels: cla-signed

#136 Clarifies the order of steps for documentation changes
  README.md
  docs/documentation_index.md
Labels: cla-signed
