Repository home-assistant/developers.home-assistant, pull requests merged in 2022-05, with the labels that each got.

#1316 Integrity check
  docs/api/supervisor/endpoints.md
Labels: cla-signed

#1320 Remove documentation of entity category system
  docs/core/entity.md
Labels: cla-signed

#1285 Blog: Deprecated constants for 2022.5
  blog/2022-05-03-constants-deprecations.md
Labels: cla-signed

#1311 ServiceInfo model improvements and deprecations
  blog/2022-05-03-serviceinfo-model-improvements.md
Labels: cla-signed

#1322 Add missing HVACAction.Fan to climate entity documentation
  docs/core/entity/climate.md
Labels: cla-signed

#1326 Tweak description of `map` addon config option
  docs/add-ons/configuration.md
Labels: cla-signed

#1327 Add blogpost about new base image
  blog/2022-05-12-s6-overlay-base-images.md
  docs/add-ons/presentation.md
Labels: cla-signed

#1329 Add note on `init: false`
  blog/2022-05-12-s6-overlay-base-images.md
  docs/add-ons/configuration.md
  docs/add-ons/tutorial.md
Labels: enhancement, cla-signed

#1241 Add tips and tricks page
  docs/creating_component_code_review.md
  docs/development_tips.md
  sidebars.js
Labels: cla-signed

#1330 Add documentation for the existing calendar rest APIs
  docs/api/rest.md
Labels: cla-signed

#1331 Add more detailed application_credentials import instructions
  docs/core/platform/application_credentials.md
Labels: cla-signed

#1328 Add documentation for custom auth implentations in application credentials
  docs/core/platform/application_credentials.md
Labels: cla-signed

#1332 Update calendar event rest AP with description and location
  docs/api/rest.md
Labels: cla-signed

#1333 Adjust auto_update for update entity
  docs/core/entity/update.md
Labels: cla-signed

#1325 Update mobile app
  docs/api/native-app-integration/sensors.md
Labels: cla-signed

#1334 Document `loggers` manifest field
  docs/creating_integration_manifest.md
Labels: cla-signed

#1336 `host_pid` does not work in s6 v3
  blog/2022-05-12-s6-overlay-base-images.md
  docs/add-ons/configuration.md
Labels: bug, cla-signed

#1337 Add codenotary to add-on config.yaml documentation
  docs/add-ons/configuration.md
Labels: cla-signed

#1338 Update options flow examples to including typing
  docs/config_entries_options_flow_handler.md
Labels: cla-signed

#1340 Document removal of entity_matches_only from logbook api
  blog/2022-05-24-entity_matches_only_removed_logbook_card.md
Labels: cla-signed

#1346 Change home-assistant to core
  docs/internationalization/core.md
Labels: cla-signed

#1347 Update some URLs
  docs/development_environment.mdx
Labels: cla-signed

#1345 Rename component to integration
  docs/api/rest.md
Labels: cla-signed

#1348 Components to integrations
  docs/documenting/create-page.md
Labels: cla-signed

#1343 Use supervisor envs instead of hassio
  docs/supervisor/development.md
Labels: cla-signed

#1341 Updates outdated procedure to SSH host access
  docs/operating-system/debugging.md
Labels: cla-signed

#1352 Document media player changes
  blog/2022-05-31-media-player-updates.md
  docs/core/entity/media-player.md
Labels: cla-signed
