Repository home-assistant/developers.home-assistant, pull requests merged in 2022-10, with the labels that each got.

#1486 Update sensor.md, to make it easier to find the section about choosing state class
  docs/core/entity/sensor.md
Labels: hacktoberfest

#1487 Rewording of a sentence in standards.md
  docs/documenting/standards.md
Labels: hacktoberfest

#1493 Add blog post for SelectEntityDescription
  blog/2020-10-10-add-options-to-SelectEntityDescription
Labels: hacktoberfest

#1494 Fix tailing comma in JSON snippet on Grouping integrations page
  docs/creating_integration_brand.md
Labels: hacktoberfest

#1496 Blog post for deprecated unit system features
  blog/2022-10-14-deprecate-unit-system.md
Labels: hacktoberfest

#1442 Document new options for supervisor backups
  docs/api/supervisor/endpoints.md
Labels: enhancement, cla-signed

#1497 Update bluetooth documentation for bleak 0.19 changes
  docs/bluetooth.md
Labels: hacktoberfest

#1501 Update development_environment.mdx
  docs/development_environment.mdx
Labels: hacktoberfest

#1504 add blog about code owner commands
  blog/2022-10-21-code-owner-commands.md
Labels: hacktoberfest

#1416 Add missing store endpoints
  docs/api/supervisor/endpoints.md
Labels: cla-signed

#1127 Add documentation for enhanced logging endpoints
  docs/api/supervisor/endpoints.md
Labels: cla-signed

#1505 Minor grammar improvements in front end developer docs
  docs/frontend/external-authentication.md
Labels: hacktoberfest

#1499 Integrations v2.1: Differentiating hubs, devices and services
  docs/creating_integration_manifest.md
Labels: hacktoberfest

#1506 Integrations v2.1: Virtual integrations
  docs/creating_integration_manifest.md
Labels: hacktoberfest

#1500 Rename IMPERIAL_SYSTEM to US_CUSTOMARY_SYSTEM
  blog/2022-10-14-deprecate-unit-system.md
Labels: hacktoberfest

#1507 Process review comments in virtual integrations
  docs/creating_integration_manifest.md
Labels: hacktoberfest

#1508 Add blog post about integrations v2.1
  blog/2022-10-24-hubs-devices-services-virtual-integrations.md
Labels: hacktoberfest

#1509 Add WATER sensor device class
  docs/core/entity/sensor.md
Labels: hacktoberfest

#1510 Make iot_standards in virtual integrations a list
  docs/creating_integration_manifest.md
Labels: hacktoberfest

#1490 Add wind_speed sensor device class
  docs/core/entity/sensor.md
Labels: hacktoberfest

#1513 Pin nodejs to 16
  .devcontainer/Dockerfile
  .nvmrc
Labels: hacktoberfest

#1502 Use the typed dataclass DeviceInfo
  docs/device_registry_index.md
Labels: hacktoberfest

#1491 Add precipitation_intensity sensor device class
  docs/core/entity/sensor.md
Labels: hacktoberfest

#1489 Adjust precipitation units
  blog/2022-10-25-new-precipitation-intensity-units.md
Labels: hacktoberfest

#1514 Bump NodeJS to 18 (current LTS)
  .devcontainer/Dockerfile
  .nvmrc
  yarn.lock
Labels: hacktoberfest

#1512 Add diagnostics to integration QA scale gold requirements
  docs/integration_quality_scale_index.md
Labels: hacktoberfest

#1511 Introducing new unit enumerators
  blog/2022-10-26-new-unit-enumerators.md
Labels: hacktoberfest

#1515 Minor typo fix
  docs/add-ons/tutorial.md
Labels: hacktoberfest

#1522 Use UTC as TZ and show TZ note for calendar embed
  src/pages/index.js
Labels: hacktoberfest
