Repository home-assistant/developers.home-assistant, pull requests merged in 2022-01, with the labels that each got.

#1171 Update developer docs to mention RTSP to WebRTC
  docs/core/entity/camera.md
Labels: cla-signed

#1173 Fix link to Auth backend documentation
  docs/add-ons/security.md
Labels: cla-signed

#1176 Switch to local search
  docusaurus.config.js
  package.json
  yarn.lock
Labels: cla-signed

#1153 Fix type for `current_humidity`
  docs/core/entity/climate.md
Labels: cla-signed

#1101 Improve platform/integration doc writing standards
  docs/documenting/standards.md
Labels: cla-signed, hacktoberfest-accepted

#1181 Fix a typo in documenting/standards
  docs/documenting/standards.md
Labels: cla-signed

#1179 Add link to source for different entities
  docs/core/entity/binary-sensor.md
  docs/core/entity/remote.md
  docs/core/entity/sensor.md
  docs/core/entity/vacuum.md
  docs/core/entity/water-heater.md
  docs/core/entity/weather.md
Labels: cla-signed

#1182 Document Subscribe to trigger websocket
  docs/api/websocket.md
Labels: cla-signed

#1174 Add documentation for 'fire_event' command in websocket api
  docs/api/websocket.md
Labels: cla-signed, cla-error

#1187 Add size to backup list endpoint
  docs/api/supervisor/endpoints.md
Labels: cla-signed

#1191 Update minimum Python version to 3.9
  docs/development_environment.mdx
Labels: cla-signed

#1189 Update development_environment.mdx
  docs/development_environment.mdx
Labels: cla-signed

#1193 Add new root endpoints
  docs/api/supervisor/endpoints.md
Labels: cla-signed

#1194 Clarify gold level quality scale test requirements
  docs/integration_quality_scale_index.md
Labels: cla-signed

#1180 Document delivering webhooks over WS
  docs/api/native-app-integration/sending-data.md
Labels: cla-signed

#1143 Added Python Example
  docs/api/rest.md
Labels: cla-signed

#1128 Line170 fixed: "options" instead of "config"
  docs/add-ons/tutorial.md
Labels: cla-signed

#1175 Minor tweaks of the Local add-on testing page
  docs/add-ons/testing.md
Labels: cla-signed

#867 Inform that recursive lookup is used for config
  docs/add-ons/configuration.md
Labels: cla-signed

#1195 Improve strings.sensor.json key wording
  docs/internationalization/core.md
Labels: cla-signed

#1196 Adds information about process
  docs/translations.md
Labels: cla-signed

#1201 Fix black editor link
  blog/2019-07-31-black.md
Labels: cla-signed

#1200 Add "reprompt" for the intent response
  docs/intent_firing.md
Labels: cla-signed

#1172 Document native app websocket push
  docs/api/native-app-integration/notifications.md
Labels: cla-signed
