Repository home-assistant/developers.home-assistant, pull requests merged in 2023-11, with the labels that each got.

#1964 Clarify image entity documentation
  docs/core/entity/image.md
Labels: hacktoberfest

#1384 Add mmHg as a valid pressure unit
  docs/core/entity/sensor.md
Labels: cla-signed

#1961 Add ServiceValidationError and translation support
  blog/2023-11-16-service-exceptions-and-translations.md
  docs/api/websocket.md
  docs/core/platform/raising_exceptions.md
  docs/integration_quality_scale_index.md
  docs/internationalization/core.md
  sidebars.js
Labels: hacktoberfest, parent-merged

#1981 Add To-do list item due and description field developer documentation
  docs/core/entity/todo.md
Labels: awaits-parent
