Repository home-assistant/developers.home-assistant, pull requests merged in 2023-10, with the labels that each got.

#1943 Add dev blog on Hacktoberfest 2023
  blog/2023-10-01-hacktoberfest-2023.md
Labels: hacktoberfest

#1942 Create blog post for clean up of deprecated unit conversion functions
  blog/2023-10-03-conversion-functions-cleanup.md
Labels: hacktoberfest

#1905 Document new endpoints for green board
  docs/api/supervisor/endpoints.md
Labels: enhancement, parent-merged

#1896 Document jobs api
  docs/api/supervisor/endpoints.md
  docs/api/supervisor/models.md
Labels: parent-merged

#1946 Fix Assist pipeline wake word stage enum value
  docs/voice/pipelines/index.md
Labels: hacktoberfest

#1950 just a : was missing
  docs/internationalization/core.md
Labels: hacktoberfest

#1929 Add todo component developer documentation
  docs/core/entity/todo.md
Labels: parent-merged

#1953 Add note about removing options
  docs/add-ons/configuration.md
Labels: hacktoberfest

#1954 Fix architecture repo link
  docs/integration_quality_scale_index.md
Labels: hacktoberfest

#1948 Blog country selector
  blog/2023-10-12-country_selector.md
Labels: hacktoberfest, parent-merged

#1955 Fix note markdown in add-on configuration section
  docs/add-ons/configuration.md
Labels: hacktoberfest

#1960 Document new addon config folder options
  docs/add-ons/configuration.md
Labels: enhancement, hacktoberfest, parent-merged

#1958 Update todo move item API to reference previous uid
  docs/core/entity/todo.md
Labels: hacktoberfest

#1963 Add entity description docs
  docs/core/entity.md
Labels: hacktoberfest
