Repository home-assistant/developers.home-assistant, pull requests merged in 2024-10, with the labels that each got.

#2304 Document assist_satellite entity component
  blog/2024-10-01-assist-satellite-entity.md
  docs/core/entity/assist-satellite.md
Labels: parent-merged

#2345 Adjust async_step_reconfigure documentation
  docs/config_entries_config_flow_handler.md
Labels: hacktoberfest

#2346 Adjust async_step_reauth documentation
  docs/config_entries_config_flow_handler.md
Labels: hacktoberfest

#2350 Update YAML style guide to new syntax
  docs/documenting/yaml-style-guide.md
Labels: hacktoberfest

#2351 Revert "Adjust async_step_reconfigure documentation (#2345)"
  docs/config_entries_config_flow_handler.md
Labels: hacktoberfest, parent-merged

#2347 Document get_reauth_entry and get_reconfigure_entry helpers
  docs/config_entries_config_flow_handler.md
Labels: hacktoberfest, parent-merged

#2354 Update guidelines to reference Ruff instead of Black as the formatter
  docs/development_guidelines.md
Labels: hacktoberfest

#2355 Remove ordering imports section in development guidelines
  docs/development_guidelines.md
Labels: hacktoberfest

#2353 Document _abort_if_unique_id_mismatch helper
  docs/config_entries_config_flow_handler.md
Labels: hacktoberfest, parent-merged

#2357 Add blog post about changes to UnitOfConductivity
  blog/2024-10-08-unit-of-conductivity-changes.md
Labels: hacktoberfest

#2348 Change cover state to enum
  blog/2024-10-08-state-constants-cover-deprecation.md
  docs/core/entity/cover.md
Labels: hacktoberfest

#2352 Adjust reauth/reconfigure documentation to highlight expected result
  docs/config_entries_config_flow_handler.md
Labels: hacktoberfest, parent-merged

#2358 Remove writing suggesting INFO logs are not allowed in integrations
  docs/development_guidelines.md
Labels: hacktoberfest

#2359 Add blog post about extension of deprecation period of hass.helpers
  blog/2024-10-09-extend-deprecation-hass-helpers.md
Labels: hacktoberfest

#2363 Update type of device_info in entity.md
  docs/core/entity.md
Labels: hacktoberfest

#2372 Add/update type information in sensor.md
  docs/core/entity/sensor.md
Labels: hacktoberfest

#2381 Minor grammar fixes in custom card docs
  docs/frontend/custom-ui/custom-card.md
Labels: hacktoberfest

#2365 Add IQS002 rule
  docs/core/integration-quality-scale/index.md
  docs/core/integration-quality-scale/rules/iqs002.md
Labels: hacktoberfest

#2376 Add IQS012 rule
  docs/core/integration-quality-scale/rules/iqs012.md
Labels: hacktoberfest

#2367 Add IQS004 rule
  docs/core/integration-quality-scale/index.md
  docs/core/integration-quality-scale/rules/iqs004.md
Labels: hacktoberfest

#2364 Add IQS001 rule
  docs/core/integration-quality-scale/index.md
  docs/core/integration-quality-scale/rules/iqs001.md
Labels: hacktoberfest

#2374 Add IQS010 rule
  docs/core/integration-quality-scale/rules/iqs010.md
Labels: hacktoberfest

#2369 Add IQS006 rule
  docs/core/integration-quality-scale/index.md
  docs/core/integration-quality-scale/rules/iqs006.md
Labels: hacktoberfest

#2375 Add IQS011 rule
  docs/core/integration-quality-scale/rules/iqs011.md
Labels: hacktoberfest

#2368 Add IQS005 rule
  docs/core/integration-quality-scale/index.md
  docs/core/integration-quality-scale/rules/iqs005.md
Labels: hacktoberfest

#2380 Add IQS016 rule
  docs/core/integration-quality-scale/rules/iqs016.md
Labels: hacktoberfest

#2370 Add IQS007 rule
  docs/core/integration-quality-scale/rules/iqs007.md
Labels: hacktoberfest

#2385 Add IQS020 rule
  docs/core/integration-quality-scale/rules/iqs020.md
Labels: hacktoberfest

#2371 Add IQS008 rule
  docs/core/integration-quality-scale/rules/iqs008.md
Labels: hacktoberfest

#2377 Add IQS013 rule
  docs/core/integration-quality-scale/rules/iqs013.md
Labels: hacktoberfest

#2356 Blog post for new helpers in reauth and reconfigure flows
  blog/2024-10-21-reauth-reconfigure-helpers.md
  docs/config_entries_config_flow_handler.md
Labels: hacktoberfest, parent-merged

#2413 Document update entity's update_percentage property
  docs/core/entity/update.md
Labels: hacktoberfest

#2361 Add new alarm state property and enum
  blog/2024-10-22-new-alarm-state-property.md
  docs/core/entity/alarm-control-panel.md
Labels: hacktoberfest, parent-merged

#2366 Add IQS003 rule
  docs/core/integration-quality-scale/index.md
  docs/core/integration-quality-scale/rules/iqs003.md
Labels: hacktoberfest

#2415 Add IQS039 rule
  docs/core/integration-quality-scale/rules/iqs039.md
Labels: hacktoberfest

#2379 Add IQS015 rule
  docs/core/integration-quality-scale/rules/iqs015.md
Labels: hacktoberfest

#2394 Add IQS029 rule
  docs/core/integration-quality-scale/rules/iqs029.md
Labels: hacktoberfest

#2390 Add IQS025 rule
  docs/core/integration-quality-scale/rules/iqs025.md
Labels: hacktoberfest

#2407 Add IQS043 rule
  docs/core/integration-quality-scale/rules/iqs043.md
Labels: hacktoberfest

#2401 Add IQS036 rule
  docs/core/integration-quality-scale/rules/iqs036.md
Labels: hacktoberfest

#2406 Add IQS042 rule
  docs/core/integration-quality-scale/rules/iqs042.md
Labels: hacktoberfest

#2387 Add IQS022 rule
  docs/core/integration-quality-scale/rules/iqs022.md
Labels: hacktoberfest

#2388 Add IQS023 rule
  docs/core/integration-quality-scale/rules/iqs023.md
Labels: hacktoberfest

#2395 Add IQS030 rule
  docs/core/integration-quality-scale/rules/iqs030.md
Labels: hacktoberfest

#2400 Add IQS035 rule
  docs/core/integration-quality-scale/rules/iqs035.md
Labels: hacktoberfest

#2398 Add IQS033 rule
  docs/core/integration-quality-scale/rules/iqs033.md
Labels: hacktoberfest

#2396 Add IQS031 rule
  docs/core/integration-quality-scale/rules/iqs031.md
Labels: hacktoberfest

#2391 Add IQS026 rule
  docs/core/integration-quality-scale/rules/iqs026.md
Labels: hacktoberfest

#2386 Add IQS021 rule
  docs/core/integration-quality-scale/rules/iqs021.md
Labels: hacktoberfest

#2383 Add IQS018 rule
  docs/core/integration-quality-scale/rules/iqs018.md
Labels: hacktoberfest

#2389 Add IQS024 rule
  docs/core/integration-quality-scale/rules/iqs024.md
Labels: hacktoberfest

#2405 Add IQS041 rule
  docs/core/integration-quality-scale/rules/iqs041.md
Labels: hacktoberfest

#2393 Add IQS028 rule
  docs/core/integration-quality-scale/rules/iqs028.md
Labels: hacktoberfest

#2378 Add IQS014 rule
  docs/core/integration-quality-scale/rules/iqs014.md
Labels: hacktoberfest

#2382 Add IQS017 rule
  docs/core/integration-quality-scale/rules/iqs017.md
Labels: hacktoberfest

#2392 Add IQS027 rule
  docs/core/integration-quality-scale/rules/iqs027.md
Labels: hacktoberfest

#2410 Update WebRTC provider documentation to reference new APIs
  docs/core/entity/camera.md
Labels: hacktoberfest
