Repository home-assistant/developers.home-assistant, pull requests merged in 2024-11, with the labels that each got.

#2409 Update WebRTC methods for async approach
  docs/core/entity/camera.md
Labels: hacktoberfest, parent-merged

#2436 Document required entry_id
  blog/2024-11-04-reauth-reconfigure-entry-id.md
Labels: parent-merged

#2431 Add blog post about update entity changes
  blog/2024-10-31-update-entity-changes.md
Labels: hacktoberfest

#2433 Add blog post about core config move
  blog/2024-10-31-core-config-moved.md
Labels: hacktoberfest

#2425 Add IQS051 rule
  docs/core/integration-quality-scale/rules/iqs051.md
Labels: hacktoberfest

#2427 Add IQS053 rule
  docs/core/integration-quality-scale/rules/iqs053.md
Labels: hacktoberfest

#2424 Add IQS050 rule
  docs/core/integration-quality-scale/rules/iqs050.md
Labels: hacktoberfest

#2404 Add IQS040 rule
  docs/core/integration-quality-scale/rules/iqs040.md
Labels: hacktoberfest

#2420 Add IQS046 rule
  docs/core/integration-quality-scale/rules/iqs046.md
Labels: hacktoberfest

#2373 Add IQS009 rule
  docs/core/integration-quality-scale/rules/iqs009.md
Labels: hacktoberfest

#2421 Add IQS047 rule
  docs/core/integration-quality-scale/rules/iqs047.md
Labels: hacktoberfest

#2417 Add IQS045 rule
  docs/core/integration-quality-scale/rules/iqs045.md
Labels: hacktoberfest

#2397 Add IQS032 rule
  docs/core/integration-quality-scale/rules/iqs032.md
Labels: hacktoberfest

#2429 Add device class for blood glucose concentration
  docs/core/entity/number.md
  docs/core/entity/sensor.md
Labels: hacktoberfest

#2399 Add IQS034 rule
  docs/core/integration-quality-scale/rules/iqs034.md
Labels: hacktoberfest

#2426 Add IQS052 rule
  docs/core/integration-quality-scale/rules/iqs052.md
Labels: hacktoberfest

#2384 Add IQS019 rule
  docs/core/integration-quality-scale/rules/iqs019.md
Labels: hacktoberfest

#2423 Add IQS049 rule
  docs/core/integration-quality-scale/rules/iqs049.md
Labels: hacktoberfest

#2435 New helpers for options flows
  blog/2024-11-12-options-flow.md
  docs/config_entries_options_flow_handler.md
Labels: parent-merged

#2416 Add IQS044 rule
  docs/core/integration-quality-scale/rules/iqs044.md
Labels: hacktoberfest

#2408 Try to make rules dynamic
  docs/core/integration-quality-scale/index.md
  docs/core/integration-quality-scale/rules/_includes/related_rules.jsx
  docs/core/integration-quality-scale/rules/_includes/rule_overview.jsx
  docs/core/integration-quality-scale/rules/_includes/tiers.json
  docs/core/integration-quality-scale/rules/iqs001.md
  docs/core/integration-quality-scale/rules/iqs002.md
  docs/core/integration-quality-scale/rules/iqs003.md
  docs/core/integration-quality-scale/rules/iqs004.md
  docs/core/integration-quality-scale/rules/iqs005.md
  docs/core/integration-quality-scale/rules/iqs006.md
  docs/core/integration-quality-scale/rules/iqs007.md
  docs/core/integration-quality-scale/rules/iqs008.md
  docs/core/integration-quality-scale/rules/iqs009.md
  docs/core/integration-quality-scale/rules/iqs010.md
  docs/core/integration-quality-scale/rules/iqs011.md
  docs/core/integration-quality-scale/rules/iqs012.md
  docs/core/integration-quality-scale/rules/iqs013.md
  docs/core/integration-quality-scale/rules/iqs014.md
  docs/core/integration-quality-scale/rules/iqs015.md
  docs/core/integration-quality-scale/rules/iqs016.md
  docs/core/integration-quality-scale/rules/iqs017.md
  docs/core/integration-quality-scale/rules/iqs018.md
  docs/core/integration-quality-scale/rules/iqs020.md
  docs/core/integration-quality-scale/rules/iqs021.md
  docs/core/integration-quality-scale/rules/iqs022.md
  docs/core/integration-quality-scale/rules/iqs023.md
  docs/core/integration-quality-scale/rules/iqs024.md
  docs/core/integration-quality-scale/rules/iqs025.md
  docs/core/integration-quality-scale/rules/iqs026.md
  docs/core/integration-quality-scale/rules/iqs027.md
  docs/core/integration-quality-scale/rules/iqs028.md
  docs/core/integration-quality-scale/rules/iqs029.md
  docs/core/integration-quality-scale/rules/iqs030.md
  docs/core/integration-quality-scale/rules/iqs031.md
  docs/core/integration-quality-scale/rules/iqs032.md
  docs/core/integration-quality-scale/rules/iqs033.md
  docs/core/integration-quality-scale/rules/iqs034.md
  docs/core/integration-quality-scale/rules/iqs035.md
  docs/core/integration-quality-scale/rules/iqs036.md
  docs/core/integration-quality-scale/rules/iqs039.md
  docs/core/integration-quality-scale/rules/iqs040.md
  docs/core/integration-quality-scale/rules/iqs041.md
  docs/core/integration-quality-scale/rules/iqs042.md
  docs/core/integration-quality-scale/rules/iqs043.md
  docs/core/integration-quality-scale/rules/iqs045.md
  docs/core/integration-quality-scale/rules/iqs046.md
  docs/core/integration-quality-scale/rules/iqs047.md
  docs/core/integration-quality-scale/rules/iqs050.md
  docs/core/integration-quality-scale/rules/iqs051.md
  docs/core/integration-quality-scale/rules/iqs052.md
  docs/core/integration-quality-scale/rules/iqs053.md
Labels: hacktoberfest

#2422 Add IQS048 rule
  docs/core/integration-quality-scale/rules/_includes/tiers.json
  docs/core/integration-quality-scale/rules/iqs017.md
  docs/core/integration-quality-scale/rules/iqs048.md
Labels: hacktoberfest

#2402 Add config flow disclaimer about how it should be used
  docs/core/integration-quality-scale/rules/iqs001.md
Labels: hacktoberfest

#2403 Add information on where to store data in the config flow to IQS
  docs/core/integration-quality-scale/rules/iqs001.md
Labels: hacktoberfest
