Repository home-assistant/developers.home-assistant, pull requests merged in 2024-12, with the labels that each got.

#2309 Update ClimateEntity for horizontal swing support
  blog/2024-12-03-climate-horizontal-swing.md
  docs/core/entity/climate.md
Labels: parent-merged

#2360 Add new vacuum state property and enum
  blog/2024-12-08-new-vacuum-state-property.md
  docs/core/entity/vacuum.md
Labels: hacktoberfest, parent-merged

#2493 Add mWh as unit of measurement
  docs/core/entity/number.md
  docs/core/entity/sensor.md
Labels: awaits-parent, has-parent

#2494 Blog about changed name of `WaterHeaterEntityDescription`
  blog/2024-12-13-water-heater-entity-description.md
Labels: parent-merged, has-parent

#2495 Blog post about Kelvin as the preferred color temperature unit
  blog/2024-12-14-kelvin-preferred-color-temperature-unit.md
Labels: parent-merged, has-parent

#2448 Add blog and update number and sensor entity docs
  blog/2024-12-26-area-squared-units.md
  docs/core/entity/number.md
  docs/core/entity/sensor.md
Labels: parent-merged
