Repository home-assistant/developers.home-assistant, pull requests merged in 2025-05, with the labels that each got.

#2661 Add liter for gas device classes
  docs/core/entity/number.md
  docs/core/entity/sensor.md
Labels: awaits-parent, has-parent

#2672 Document that 1-shot TTS is still needed
  docs/core/entity/tts.md
Labels: awaits-parent, has-parent

#2676 Add range support to icon translations
  blog/2025-05-22-range-based-icons.md
  docs/core/integration-quality-scale/rules/icon-translations.md
Labels: parent-merged, has-parent

#2675 Add concentration conversion support for mg/m³
  docs/core/entity/number.md
  docs/core/entity/sensor.md
Labels: has-parent

#2680 Update config flow docs for read-only selectors
  docs/data_entry_flow_index.md
Labels: awaits-parent
