Repository home-assistant/developers.home-assistant, pull requests merged in 2025-07, with the labels that each got.

#2695 Remove battery properties from vacuum entity
  blog/2025-07-02-vacuum-battery-properties-deprecated.md
  docs/core/entity/vacuum.md
Labels: has-parent

#2721 Add new device class for absolute humidity
  docs/core/entity/number.md
  docs/core/entity/sensor.md
Labels: awaits-parent

#2696 Document provide LLM data
  docs/core/llm/index.md
Labels: parent-merged
